# Generated by Django 4.2.7 on 2023-11-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='library/categories/')),
                ('No_of_items', models.IntegerField()),
                ('isblocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to='library/products/')),
                ('image2', models.ImageField(blank=True, upload_to='library/products/')),
                ('image3', models.ImageField(blank=True, upload_to='library/products/')),
                ('image4', models.ImageField(blank=True, upload_to='library/products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_admin.book_category')),
            ],
        ),
    ]
